Extract SplitButton into tdesign
splitgraph/splitgraph.com pull request #173
Opened 2022-02-09 14:21 UTC by onpaws

- Unlike the other data source related changes, this has a higher potential for re-use and seems appropriate for tdesign
- SplitButton, while a WIP right now, is being considered for the repo page's data source widget

- CU-29a25tx

2022-02-09 14:22 UTC, onpaws commented
tiny little screenshot of the wip <img width="448" alt="image" src="https://user-images.githubusercontent.com/182515/153220130-a289c464-d1df-43c9-96f0-dca681708523.png">

2022-02-10 12:53 UTC, Gelio requested changes
> this has a higher potential for re-use and seems appropriate for tdesign

Where do you guess it could be used, other than the parent repository :slightly_smiling_face: ? I'd only move components into `tdesign` if they have to be used by other components inside `tdesign`. If that does not apply, I suggest keeping components inside the parent repository, as it is easier to modify them there.

In the case of this component, I don't see where it can be used inside other components of `tdesign`. I suppose it will only be used in the pages in the parent repository. Thus, I suggest moving it there

---

I didn't review the code for this component. I only wanted to make this note before we start reviewing it, to host the review in the appropriate place :slightly_smiling_face:

2022-02-10 20:40 UTC, onpaws commented
Replied on chat, lets review whenever you get a chance :)

2022-02-13 16:54 UTC, onpaws commented
Closing this PR for the reasons discussed on chat. To be continued in the catalog repo

2022-02-13 16:54 UTC, closed without merging